name: Primer Pipeline Práctico

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] #se activara cuando alguien abra una pr hacia el main

jobs:
  verificacion:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22] ## Definimos las tres versiones que queremos probar

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Saludo en la terminal
        run: echo "¡Hola mundo! El pipeline se está ejecutando correctamente."

      - name: Mostrar archivos del repositorio
        run: ls -la

      - name: Configurar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Usamos la misma versión que instalaste en tu PC 
      
      - name: Instalar dependencias de React
        run: npm ci

      - name: Compilar el proyecto
        run: npm run build

      - name: Desplegar a producción
        if: matrix.node-version == '22'  ## Solo se ejecutará en la versión 22
        run: echo "Desplegando a producción con exito en el servidor"
        