name: Node.js CI/CD

on:
  push:
    branches: [ main, master ] # Se activa al empujar cambios a estas ramas

permissions:
  contents: write # Permiso crucial para que GitHub Actions pueda publicar la página por ti

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio 
        uses: actions/checkout@v4

      - name: Configurar Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependencias de React 
        run: npm ci

      - name: Ejecutar pruebas automatizadas 
        run: npm run test

      - name: Compilar el proyecto 
        run: npm run build

      - name: Desplegar en GitHub Pages 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # La carpeta que genera React con tu app optimizada
          branch: gh-pages # La rama especial donde se guardará la web pública